# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd8310a4f0f4015dabc6385b4ee44ddf5f06117a8dbe19cc7223682f82abf3bbdda41b105e907d7da5c0ba4511e21ed560b3f8f242f601a94b62aa4179ca1c5

test:
  secret_key_base: 7152fcd4cb7ff861e2562e7d2141d671de23b390f401ae4324157576cccc153e7b442d6e7b4377928e22e37ba66cab39b5005186162a297598a6b5b0352d8160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
